name: CI

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
      - run: |
          ./VirgilsPSToolkit/build/build.ps1
