name: main

on: 
  push:
    branches: [ main ]
    paths:
      - 'VirgilsPSToolkit/functions/**.ps1'
      - 'VirgilsPSToolkit/VirgilsPSToolkit.psd1'
      - 'VirgilsPSToolkit/VirgilsPSToolkit.psm1'

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          ./VirgilsPSToolkit/build/build.ps1

      - name: Test
        run: |
          ./VirgilsPSToolkit/build/test.ps1
          
      - name: Publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: |
          ./VirgilsPSToolkit/build/publish.ps1
