name: CI

on: push
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - run: |
          ./VirgilsPSToolkit/build/variables.ps1
