name: CI

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish        
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: |
          ./VirgilsPSToolkit/build/build.ps1
          ./VirgilsPSToolkit/build/publish.ps1
